sudo: required
language: python
services:
  - docker
addons:
  apt:
    sources:
      - sourceline: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu trusty stable'
        key_url: 'https://download.docker.com/linux/ubuntu/gpg'
    packages:
      - docker-ce

matrix:
  include:
    - os: linux
      env: SCENARIO="default"
      python: 3.6
    - os: linux
      env: SCENARIO="default"
      python: 2.7
    - os: osx
      env: SCENARIO="macos"
      python: 3.6

install:
  - pip install molecule docker-py

script:
  - molecule test --scenario-name $SCENARIO

notifications:
  webhooks: 
    - https://galaxy.ansible.com/api/v1/notifications/
  only: master