---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    ansible_connection_options:
      ansible_connection: local
lint:
  name: yamllint
platforms:
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: macos
  test_sequence:
    - lint
    - dependency
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - destroy
verifier:
  name: testinfra
  lint:
    name: flake8
