---
- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    gpgcheck: false
- name: Install rclone
  yum:
    update_cache: true
    name: rclone
    state: present
- name: Set Supported
  set_fact:
    supported: true
