---
- name: Setting supported to false
  set_fact:
    supported: false
- name: Install rclone for Red Hat family
  include_tasks: centos.yml
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'
- name: Install rclone for Fedora
  include_tasks: fedora.yml
  when: ansible_distribution == 'Fedora'
- name: Install rclone for Debian family
  include_tasks: debian.yml
  when: (ansible_distribution == 'Ubuntu' and ansible_distribution_major_version|int >= 18) or ansible_distribution == 'Debian'
- name: Install rclone for Archlinux
  include_tasks: archlinux.yml
  when: ansible_distribution == 'Archlinux'
- name: Install rclone for OpenSUSE
  include_tasks: opensuse.yml
  when: ansible_distribution == 'OpenSUSE'
- name: Install rclone for macOS
  include_tasks: macosx.yml
  when: ansible_os_family == 'Darwin'
- name: Install rclone for FreeBSD
  include_tasks: freebsd.yml
  when: ansible_os_family == 'FreeBSD'
- name: Install rclone for Windows
  include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
