---  # This part is COPIED from https://github.com/stefangweichinger/ansible-rclone
- name: Create temporary working directory
  file:
    path: "{{ rclone_setup_tmp_dir }}"
    state: directory
    mode: 0775
- block:
    - name: Check latest stable rclone version number
      uri:
        url: https://downloads.rclone.org/version.txt
        return_content: true
      register:
        rclone_latest_version
    - set_fact:
        rclone_version: "{{ rclone_latest_version.content | replace ('rclone v', '', 1) | trim }}"
- name: Update repositories cache on Ubuntu Xenial
  apt:
    update_cache: true
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'
- name: Install required packages
  package:
    name: unzip
    state: present
- name: Get rclone stable version
  unarchive:
    src: https://downloads.rclone.org/v{{ rclone_version }}/rclone-v{{ rclone_version }}-linux-{{ rclone_architectures[ansible_architecture] }}.zip
    dest: "{{ rclone_setup_tmp_dir }}"
    remote_src: true
    creates: "{{ rclone_setup_tmp_dir }}/rclone-v{{ rclone_version }}-linux-{{ rclone_architectures[ansible_architecture] }}"
- name: Copy rclone binary
  copy:
    src: "{{ rclone_setup_tmp_dir}}/rclone-v{{ rclone_version }}-linux-{{ rclone_architectures[ansible_architecture] }}/rclone"
    dest: "/usr/bin/rclone"
    mode: 0755
    owner: root
    group: root
    remote_src: true
